#ifndef HMC5883L_DRIVER_H
#define HMC5883L_DRIVER_H

#define CONFIGURETION_REG_A 	0x00
#define CONFIGURETION_REG_B 	0x01
#define MODE_REG 		0x02
#define REG_AXIS_X_MSB 	0x03
#define REG_AXIS_X_LSB 	0x04
#define REG_AXIS_Y_MSB 	0x05
#define REG_AXIS_Y_LSB 	0x06
#define REG_AXIS_Z_MSB 	0x07
#define REG_AXIS_Z_LSB 	0x08
#define STATUS_REG 		0x09
#define IDENTIFICATION_REG_A 	0x0A
#define IDENTIFICATION_REG_B 	0x0B
#define IDENTIFICATION_REG_C 	0x0C

#endif /* HMC5883L_DRIVER_H */
